---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
        listen 80 default_server;
        server_name  _;
        default_type text/plain;

        root /www/data;

        location /files {}

        location / {
            return 200 '< -- Pod info -- >\nHOSTNAME: $hostname\nIP: $server_addr\n< -- Request Info -- >\n$request\n';
        }
    }
